### ISSUE TITLE
Issues with kaminari

### ISSUE THREAD

**Issue by TvL2386** [richardrails/ransack_memory#5] opened 2019-11-28 10:25 UTC
Hi,

I fixed the "First" page link as per your documentation, also had to do `params.merge({...}).to_unsafe_h` to not get an exception.

The "Prev" and "1" page buttons have the same issue when you are on page 2.

<del>Another thing I ran into, which seems weird to me, is that the "clear filter" link does not clear which page you are on. The search filter is gone, but it will remember the page you are currently on. So when going back to the page without `?page=123`, you jump to the page you were on. Which is counterintuitive and not directly obvious after you clicked the link.</del> 
Edit: can't reproduce anymore

Kind regards,
TvL2386

**Comment by richardrails** [comment] 2019-12-19 14:53
This is weird, I can't reproduce it too. When you fix kaminari issue, it should work. I close this issue now, but if you get this issue in future, I will open it. Thx and happy Christmass

**Closed as completed** 2019-12-19 14:53 UTC
